LOCAL_MODULE   :=
LOCAL_SRC_DIRS :=
LOCAL_CFLAGS   :=
LOCAL_LDFLAGS  :=
LOCAL_SRC_FILES :=
LOCAL_EXCLUDE  :=
LOCAL_SECTION_NAME :=

LOCAL_PKG_NAME      :=
LOCAL_PKG_SRC       :=
LOCAL_PKG_DEPS      :=
LOCAL_PKG_OPTS      :=
LOCAL_PKG_PATCHES   :=
LOCAL_PKG_EXPORT    :=
LOCAL_IS_HOST_MODULE:=

